"""PCB AiD AI configuration module."""
from .config import (
    OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL,
    DEFAULT_MODEL,
    FALLBACK_MODEL,
    ANALYSIS_TEMPERATURE,
    OPTIMIZATION_TEMPERATURE,
    TRACE_LENGTH_THRESHOLD,
    COMPONENT_COUNT_THRESHOLD
)

__all__ = [
    "OPENROUTER_API_KEY",
    "OPENROUTER_BASE_URL",
    "DEFAULT_MODEL",
    "FALLBACK_MODEL",
    "ANALYSIS_TEMPERATURE",
    "OPTIMIZATION_TEMPERATURE",
    "TRACE_LENGTH_THRESHOLD",
    "COMPONENT_COUNT_THRESHOLD"
] 